name: Deploy to Lolipop

on:
  push:
    branches:
      - main  # Tsuchidaさんのブランチ名がもし 'master' ならここを master に変えてください

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Send to Lolipop
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/  # デスクトップのpublicフォルダの中身を送る
          server-dir: ./imglive/        # ロリポップ側の指定フォルダ直下に展開